workflows:
  ios-app:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install CocoaPods
        script: |
          gem install cocoapods
          cd ios
          pod install --repo-update
      - name: Build iOS App
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa
