// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLVmPAr7tG27sSrMCdhfhvgaNTwlfeuqg',
    appId: '1:497729458678:web:025ea3e872b40a1a2cf7d7',
    messagingSenderId: '497729458678',
    projectId: 'foreign-e6040',
    authDomain: 'foreign-e6040.firebaseapp.com',
    storageBucket: 'foreign-e6040.firebasestorage.app',
    measurementId: 'G-PVVP8KHRC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgTukUaL5oSSSCG0y6i-g48HwGsE5Wt4M',
    appId: '1:497729458678:android:b8a53f74eafc0c2b2cf7d7',
    messagingSenderId: '497729458678',
    projectId: 'foreign-e6040',
    storageBucket: 'foreign-e6040.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5BGVuQI73mikGL4njLt0PXhN33CYv7Mc',
    appId: '1:497729458678:ios:b3f40c2a39d278b22cf7d7',
    messagingSenderId: '497729458678',
    projectId: 'foreign-e6040',
    storageBucket: 'foreign-e6040.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5BGVuQI73mikGL4njLt0PXhN33CYv7Mc',
    appId: '1:497729458678:ios:b3f40c2a39d278b22cf7d7',
    messagingSenderId: '497729458678',
    projectId: 'foreign-e6040',
    storageBucket: 'foreign-e6040.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLVmPAr7tG27sSrMCdhfhvgaNTwlfeuqg',
    appId: '1:497729458678:web:8cc6a45bf93f06f42cf7d7',
    messagingSenderId: '497729458678',
    projectId: 'foreign-e6040',
    authDomain: 'foreign-e6040.firebaseapp.com',
    storageBucket: 'foreign-e6040.firebasestorage.app',
    measurementId: 'G-CDC1GR5QM3',
  );
}
